// API Configuration
export const API_CONFIG = {
  BASE_URL: 'https://www.alphavantage.co/query',
  API_KEY: '8O0DX096H6DE3L55',
  ENDPOINTS: {
    TOP_GAINERS_LOSERS: 'TOP_GAINERS_LOSERS',
    COMPANY_OVERVIEW: 'OVERVIEW',
    TIME_SERIES_DAILY: 'TIME_SERIES_DAILY',
    TIME_SERIES_WEEKLY: 'TIME_SERIES_WEEKLY',
    TIME_SERIES_MONTHLY: 'TIME_SERIES_MONTHLY',
    TIME_SERIES_INTRADAY: 'TIME_SERIES_INTRADAY',
  },
  TIMEOUT: 10000, // 10 seconds
};

// API Response status codes
export const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};
